[project]
name = "ligand_mpnn"
version = "0.1.2"
description = "Ligand MPNN Python Package"
authors = []
platforms = ["linux-64"]
preview = ["pixi-build"]


channels = [
    "dglteam/label/cu118",
    "pytorch",
    "https://conda.rosettacommons.org",
    "conda-forge",
    "nvidia"
]
channel-priority = "disabled"


[dependencies]
hatchling = "==1.26.3"
python = ">=3.9,<3.10"
python-build = "*"

[tasks]
build-wheel = "python -m build --wheel"
