name: Build and Upload Python Package

on:
  workflow_dispatch:

jobs:
  build-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Build package with pixi
        run: |
          pixi run build-wheel

      - name: Install Twine
        run: pip install --upgrade twine packaging

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*.whl
